###sign in
POST http://localhost:3100/users/login HTTP/1.1
content-type: application/json

{
    "email":"ashikshuvo1997@gmail.com",
    "password":"123456"
}

###sign up
POST http://localhost:3100/users HTTP/1.1
content-type: application/json

{
    "firstName":"ashik",
    "lastName":"ahmmed",
    "email":"ashikshuvo1997@gmail.com",
    "phoneNumber":"01730959501",
    "password":"123456"
}